import type { MetricConfig, MetricId, IndustryId, RoleId } from '../types/analytics';

// ============================================
// Complete Metrics Configuration
// Based on Industry vs Role Analytics Spec
// ============================================

export const METRICS: MetricConfig[] = [
  // ============================================
  // LOGISTICS INDUSTRY METRICS
  // ============================================
  
  // Fleet Operations Manager - Logistics
  {
    id: 'vehicle_utilization_rate',
    label: 'Vehicle Utilization Rate',
    description: '% of time the asset is actually in use vs idle',
    businessValue: 'Optimizes fleet size; exposes under-used assets',
    industry: 'logistics',
    roles: ['fleet_operations_manager', 'operations_director'],
    group: 'Utilization',
    unit: 'percentage',
    directionality: 'higher_is_better',
    chartType: 'gauge',
    defaultTimeRange: '30d',
    tags: ['efficiency', 'utilization'],
    thresholds: { warning: 60, critical: 40 },
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'idle_time',
    label: 'Idle Time',
    description: 'Engine running while not moving',
    businessValue: 'Cuts fuel waste; improves operational discipline',
    industry: 'logistics',
    roles: ['fleet_operations_manager'],
    group: 'Efficiency',
    unit: 'hours',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '30d',
    tags: ['fuel', 'efficiency'],
    thresholds: { warning: 2, critical: 4 },
    format: { decimals: 1, suffix: ' hrs' },
  },
  {
    id: 'tco_per_mile',
    label: 'TCO / Maintenance Cost per Mile',
    description: 'Cost to operate/maintain per mile and over lifecycle',
    businessValue: 'Shows when to retire/replace vehicles',
    industry: 'logistics',
    roles: ['fleet_operations_manager', 'maintenance_manager'],
    group: 'Cost',
    unit: 'currency',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '90d',
    tags: ['cost', 'maintenance'],
    format: { decimals: 2, prefix: '$' },
  },
  {
    id: 'stops_per_trip',
    label: 'Stops per Trip / Deliveries per Route',
    description: 'Number of completed stops per route/day',
    businessValue: 'Increases route density; lowers unit cost',
    industry: 'logistics',
    roles: ['fleet_operations_manager'],
    group: 'Productivity',
    unit: 'number',
    directionality: 'higher_is_better',
    chartType: 'bar',
    defaultTimeRange: '7d',
    tags: ['productivity', 'delivery'],
    format: { decimals: 1 },
  },
  {
    id: 'dwell_time',
    label: 'Dwell Time',
    description: 'Time spent waiting at depots, warehouses, customer sites',
    businessValue: 'Identifies process bottlenecks; increases throughput',
    industry: 'logistics',
    roles: ['fleet_operations_manager'],
    group: 'Efficiency',
    unit: 'duration',
    directionality: 'lower_is_better',
    chartType: 'bar',
    defaultTimeRange: '30d',
    tags: ['efficiency', 'waiting'],
    thresholds: { warning: 30, critical: 60 },
    format: { decimals: 0, suffix: ' min' },
  },
  {
    id: 'on_time_delivery_rate',
    label: 'On-Time Delivery Rate',
    description: '% of deliveries made on or before schedule',
    businessValue: 'Improves customer satisfaction and SLA compliance',
    industry: 'logistics',
    roles: ['fleet_operations_manager', 'operations_director'],
    group: 'Performance',
    unit: 'percentage',
    directionality: 'higher_is_better',
    chartType: 'kpi',
    defaultTimeRange: '30d',
    tags: ['delivery', 'sla'],
    thresholds: { warning: 90, critical: 80 },
    format: { decimals: 1, suffix: '%' },
  },
  
  // Maintenance Manager - Logistics
  {
    id: 'preventive_maintenance_compliance',
    label: 'Preventive Maintenance Compliance',
    description: '% of services performed on schedule',
    businessValue: 'Reduces breakdowns and unplanned downtime',
    industry: 'logistics',
    roles: ['maintenance_manager'],
    group: 'Maintenance',
    unit: 'percentage',
    directionality: 'higher_is_better',
    chartType: 'gauge',
    defaultTimeRange: '30d',
    tags: ['maintenance', 'compliance'],
    thresholds: { warning: 85, critical: 70 },
    format: { decimals: 1, suffix: '%' },
  },
  
  // Safety & Compliance Manager - Logistics
  {
    id: 'speeding_incidents',
    label: 'Speeding Incidents',
    description: 'Number of over-speed events',
    businessValue: 'Reduces accident risk and insurance cost',
    industry: 'logistics',
    roles: ['safety_compliance_manager'],
    group: 'Safety',
    unit: 'number',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '30d',
    tags: ['safety', 'speeding'],
    thresholds: { warning: 10, critical: 25 },
    format: { decimals: 0 },
  },
  
  // Security Manager - Logistics
  {
    id: 'geofence_alerts',
    label: 'Geofence Alerts',
    description: 'Unauthorized exits/entries or after-hours movement',
    businessValue: 'Prevents theft/misuse; strengthens route adherence',
    industry: 'logistics',
    roles: ['security_manager'],
    group: 'Security',
    unit: 'number',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '7d',
    tags: ['security', 'geofence'],
    thresholds: { warning: 5, critical: 15 },
    format: { decimals: 0 },
  },

  // ============================================
  // HEAVY MACHINERY INDUSTRY METRICS
  // ============================================
  
  // Fleet Operations Manager - Heavy Machinery
  {
    id: 'equipment_utilization_rate',
    label: 'Equipment Utilization Rate',
    description: '% of available time the machine is actually working (engine hours vs available hours)',
    businessValue: 'Identifies under/overused machines; informs fleet right-sizing and allocation',
    industry: 'heavy_machinery',
    roles: ['fleet_operations_manager', 'operations_director'],
    group: 'Utilization',
    unit: 'percentage',
    directionality: 'higher_is_better',
    chartType: 'gauge',
    defaultTimeRange: '30d',
    tags: ['utilization', 'equipment'],
    thresholds: { warning: 50, critical: 30 },
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'equipment_idle_time',
    label: 'Idle Time %',
    description: 'Engine running while machine is stationary',
    businessValue: 'Cuts fuel waste; reduces unnecessary wear; improves operator discipline',
    industry: 'heavy_machinery',
    roles: ['fleet_operations_manager'],
    group: 'Efficiency',
    unit: 'percentage',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '30d',
    tags: ['idle', 'fuel'],
    thresholds: { warning: 20, critical: 35 },
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'geofence_compliance',
    label: 'Geofence Compliance',
    description: 'Alerts when equipment leaves assigned zones or enters restricted ones',
    businessValue: 'Prevents misuse, equipment hoarding, and unauthorized movement',
    industry: 'heavy_machinery',
    roles: ['fleet_operations_manager', 'security_manager'],
    group: 'Compliance',
    unit: 'percentage',
    directionality: 'higher_is_better',
    chartType: 'kpi',
    defaultTimeRange: '7d',
    tags: ['geofence', 'compliance'],
    thresholds: { warning: 90, critical: 75 },
    format: { decimals: 1, suffix: '%' },
  },
  
  // Maintenance Manager - Heavy Machinery
  {
    id: 'equipment_availability',
    label: 'Equipment Availability (%)',
    description: '(Scheduled Hours - Downtime) / Scheduled Hours',
    businessValue: 'Measures readiness; low availability directly threatens project timelines',
    industry: 'heavy_machinery',
    roles: ['maintenance_manager', 'operations_director'],
    group: 'Availability',
    unit: 'percentage',
    directionality: 'higher_is_better',
    chartType: 'gauge',
    defaultTimeRange: '30d',
    tags: ['availability', 'uptime'],
    thresholds: { warning: 85, critical: 70 },
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'mttr',
    label: 'MTTR (Mean Time to Repair)',
    description: 'Total repair time / number of repairs',
    businessValue: 'Reduces downtime; informs staffing and spare-parts decisions',
    industry: 'heavy_machinery',
    roles: ['maintenance_manager'],
    group: 'Maintenance',
    unit: 'hours',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '90d',
    tags: ['repair', 'downtime'],
    thresholds: { warning: 8, critical: 24 },
    format: { decimals: 1, suffix: ' hrs' },
  },
  {
    id: 'pm_compliance_heavy',
    label: 'Preventive Maintenance Compliance',
    description: '% of services completed on time',
    businessValue: 'Extends equipment life; reduces catastrophic failures and cost spikes',
    industry: 'heavy_machinery',
    roles: ['maintenance_manager'],
    group: 'Maintenance',
    unit: 'percentage',
    directionality: 'higher_is_better',
    chartType: 'gauge',
    defaultTimeRange: '30d',
    tags: ['maintenance', 'compliance'],
    thresholds: { warning: 80, critical: 60 },
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'maintenance_cost_per_hour',
    label: 'Maintenance Cost per Operating Hour',
    description: 'Total maintenance cost ÷ actual operating hours',
    businessValue: 'Clear lifecycle economics; exposes aging machines that should be retired',
    industry: 'heavy_machinery',
    roles: ['maintenance_manager', 'operations_director'],
    group: 'Cost',
    unit: 'currency',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '90d',
    tags: ['cost', 'maintenance'],
    format: { decimals: 2, prefix: '$' },
  },
  
  // Safety & Compliance Manager - Heavy Machinery
  {
    id: 'overspeed_incidents',
    label: 'Overspeed Incidents',
    description: 'Times equipment exceeds site speed thresholds',
    businessValue: 'Lowers accident risk and insurance costs; strengthens operator discipline',
    industry: 'heavy_machinery',
    roles: ['safety_compliance_manager'],
    group: 'Safety',
    unit: 'number',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '30d',
    tags: ['safety', 'speed'],
    thresholds: { warning: 5, critical: 15 },
    format: { decimals: 0 },
  },
  {
    id: 'geofence_safety_alerts',
    label: 'Geofence Safety Alerts',
    description: 'Entries into hazardous/restricted zones',
    businessValue: 'Prevents accidents (e.g., unauthorized blast zone entry)',
    industry: 'heavy_machinery',
    roles: ['safety_compliance_manager'],
    group: 'Safety',
    unit: 'number',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '7d',
    tags: ['safety', 'geofence'],
    thresholds: { warning: 3, critical: 10 },
    format: { decimals: 0 },
  },
  
  // Security Manager - Heavy Machinery
  {
    id: 'after_hours_usage',
    label: 'After-Hours Usage',
    description: 'Equipment used outside approved schedules',
    businessValue: 'Detects misuse, unauthorized jobs, or theft attempts',
    industry: 'heavy_machinery',
    roles: ['security_manager'],
    group: 'Security',
    unit: 'number',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '7d',
    tags: ['security', 'unauthorized'],
    thresholds: { warning: 2, critical: 5 },
    format: { decimals: 0 },
  },
  {
    id: 'tampering_alerts',
    label: 'Tampering Alerts',
    description: 'Attempts to disable GPS or remove tracking devices',
    businessValue: 'Enables escalation and physical security improvements',
    industry: 'heavy_machinery',
    roles: ['security_manager'],
    group: 'Security',
    unit: 'number',
    directionality: 'lower_is_better',
    chartType: 'kpi',
    defaultTimeRange: '30d',
    tags: ['security', 'tampering'],
    thresholds: { warning: 1, critical: 3 },
    format: { decimals: 0 },
  },
  
  // Operations Director - Heavy Machinery
  {
    id: 'overall_fleet_utilization',
    label: 'Overall Fleet Utilization',
    description: 'Average utilization across all equipment',
    businessValue: 'Strategic sizing of fleet; supports "buy, rent, or reallocate" decisions',
    industry: 'heavy_machinery',
    roles: ['operations_director'],
    group: 'Strategy',
    unit: 'percentage',
    directionality: 'higher_is_better',
    chartType: 'kpi',
    defaultTimeRange: '30d',
    tags: ['utilization', 'strategy'],
    thresholds: { warning: 60, critical: 40 },
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'total_fleet_downtime',
    label: 'Total Fleet Downtime',
    description: 'Aggregated downtime hours or %',
    businessValue: 'High-level reliability insight; directly affects jobsite throughput',
    industry: 'heavy_machinery',
    roles: ['operations_director'],
    group: 'Performance',
    unit: 'percentage',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '30d',
    tags: ['downtime', 'reliability'],
    thresholds: { warning: 15, critical: 25 },
    format: { decimals: 1, suffix: '%' },
  },

  // ============================================
  // COLD CHAIN INDUSTRY METRICS
  // ============================================
  
  // Fleet Operations Manager - Cold Chain
  {
    id: 'realtime_fleet_status',
    label: 'Real-Time Fleet Status',
    description: 'Live GPS + real-time temperature for each reefer unit',
    businessValue: 'Immediate visibility; early issue detection',
    industry: 'cold_chain',
    roles: ['fleet_operations_manager'],
    group: 'Monitoring',
    unit: 'number',
    directionality: 'higher_is_better',
    chartType: 'kpi',
    defaultTimeRange: '7d',
    tags: ['realtime', 'monitoring'],
    format: { decimals: 0 },
  },
  {
    id: 'on_time_delivery_cold',
    label: 'On-Time Delivery Rate',
    description: '% of shipments arriving on schedule',
    businessValue: 'Ensures product integrity and service quality',
    industry: 'cold_chain',
    roles: ['fleet_operations_manager', 'operations_director'],
    group: 'Performance',
    unit: 'percentage',
    directionality: 'higher_is_better',
    chartType: 'gauge',
    defaultTimeRange: '30d',
    tags: ['delivery', 'performance'],
    thresholds: { warning: 95, critical: 85 },
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'temperature_alerts',
    label: 'Temperature / Equipment Alerts',
    description: 'Automatic alerts for high temp, reefer failure, route deviation',
    businessValue: 'Enables rapid intervention before product loss',
    industry: 'cold_chain',
    roles: ['fleet_operations_manager', 'safety_compliance_manager'],
    group: 'Alerts',
    unit: 'number',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '7d',
    tags: ['temperature', 'alerts'],
    thresholds: { warning: 5, critical: 15 },
    format: { decimals: 0 },
  },
  {
    id: 'door_reefer_status',
    label: 'Door Open / Reefer Status',
    description: 'Real-time door events and reefer on/off',
    businessValue: 'Prevents temperature rise due to mistakes or tampering',
    industry: 'cold_chain',
    roles: ['fleet_operations_manager'],
    group: 'Monitoring',
    unit: 'number',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '7d',
    tags: ['door', 'reefer'],
    thresholds: { warning: 10, critical: 25 },
    format: { decimals: 0 },
  },
  {
    id: 'vehicle_dwell_time',
    label: 'Vehicle Dwell Time',
    description: 'Time spent at docks, checkpoints, customer sites',
    businessValue: 'Reduces heat-exposure risk; improves flow and efficiency',
    industry: 'cold_chain',
    roles: ['fleet_operations_manager'],
    group: 'Efficiency',
    unit: 'duration',
    directionality: 'lower_is_better',
    chartType: 'bar',
    defaultTimeRange: '30d',
    tags: ['dwell', 'efficiency'],
    thresholds: { warning: 45, critical: 90 },
    format: { decimals: 0, suffix: ' min' },
  },
  {
    id: 'fleet_utilization_cold',
    label: 'Fleet Utilization & Availability',
    description: '% of reefer trucks in use; downtime tracking',
    businessValue: 'Optimizes fleet size; reduces idle assets and service delays',
    industry: 'cold_chain',
    roles: ['fleet_operations_manager', 'operations_director'],
    group: 'Utilization',
    unit: 'percentage',
    directionality: 'higher_is_better',
    chartType: 'gauge',
    defaultTimeRange: '30d',
    tags: ['utilization', 'availability'],
    thresholds: { warning: 70, critical: 50 },
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'cost_per_shipment',
    label: 'Cost per Mile / Shipment',
    description: 'Fuel, labor, maintenance per mile or per delivery',
    businessValue: 'Identifies inefficiencies; improves route economics',
    industry: 'cold_chain',
    roles: ['fleet_operations_manager'],
    group: 'Cost',
    unit: 'currency',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '30d',
    tags: ['cost', 'efficiency'],
    format: { decimals: 2, prefix: '$' },
  },
  
  // Safety & Compliance Manager - Cold Chain
  {
    id: 'compliance_dashboard',
    label: 'Compliance Dashboard',
    description: 'Violations, active alerts, % of shipments fully compliant',
    businessValue: 'Monitors quality in real time; drives continuous improvement',
    industry: 'cold_chain',
    roles: ['safety_compliance_manager', 'operations_director'],
    group: 'Compliance',
    unit: 'percentage',
    directionality: 'higher_is_better',
    chartType: 'gauge',
    defaultTimeRange: '30d',
    tags: ['compliance', 'quality'],
    thresholds: { warning: 95, critical: 85 },
    format: { decimals: 1, suffix: '%' },
  },

  // ============================================
  // LEASING INDUSTRY METRICS
  // ============================================
  
  // Fleet Operations Manager - Leasing
  {
    id: 'idle_time_leasing',
    label: 'Idle Time %',
    description: 'Engine-on but stationary time',
    businessValue: 'Cuts fuel waste and unnecessary engine wear',
    industry: 'leasing',
    roles: ['fleet_operations_manager'],
    group: 'Efficiency',
    unit: 'percentage',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '30d',
    tags: ['idle', 'fuel'],
    thresholds: { warning: 15, critical: 30 },
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'avg_distance_per_vehicle',
    label: 'Avg Distance/Hours per Vehicle',
    description: 'Typical use intensity per asset',
    businessValue: 'Detects underused or overworked units to rebalance utilization',
    industry: 'leasing',
    roles: ['fleet_operations_manager'],
    group: 'Utilization',
    unit: 'distance',
    directionality: 'neutral',
    chartType: 'bar',
    defaultTimeRange: '30d',
    tags: ['distance', 'utilization'],
    format: { decimals: 0, suffix: ' km' },
  },
  {
    id: 'vehicle_availability_uptime',
    label: 'Vehicle Availability/Uptime',
    description: '% of time asset is operational vs in repair',
    businessValue: 'Ensures high availability to lessees; reduces service disruptions',
    industry: 'leasing',
    roles: ['fleet_operations_manager', 'maintenance_manager'],
    group: 'Availability',
    unit: 'percentage',
    directionality: 'higher_is_better',
    chartType: 'gauge',
    defaultTimeRange: '30d',
    tags: ['availability', 'uptime'],
    thresholds: { warning: 90, critical: 80 },
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'route_plan_vs_actual',
    label: 'Route Plan vs Actual',
    description: 'Actual vs planned time/distance',
    businessValue: 'Exposes systemic inefficiencies in routing',
    industry: 'leasing',
    roles: ['fleet_operations_manager'],
    group: 'Efficiency',
    unit: 'percentage',
    directionality: 'higher_is_better',
    chartType: 'bar',
    defaultTimeRange: '30d',
    tags: ['routing', 'efficiency'],
    thresholds: { warning: 85, critical: 70 },
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'empty_miles',
    label: 'Empty Miles %',
    description: '% of miles with no cargo',
    businessValue: 'Improves load planning; increases profitability',
    industry: 'leasing',
    roles: ['fleet_operations_manager'],
    group: 'Efficiency',
    unit: 'percentage',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '30d',
    tags: ['empty', 'efficiency'],
    thresholds: { warning: 20, critical: 35 },
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'stops_per_day',
    label: 'Stops/Deliveries per Day',
    description: 'Productivity indicator for leased vehicles',
    businessValue: 'Increases revenue per vehicle; detects underperforming runs',
    industry: 'leasing',
    roles: ['fleet_operations_manager'],
    group: 'Productivity',
    unit: 'number',
    directionality: 'higher_is_better',
    chartType: 'bar',
    defaultTimeRange: '7d',
    tags: ['productivity', 'stops'],
    format: { decimals: 1 },
  },
  
  // Maintenance Manager - Leasing
  {
    id: 'downtime_planned_unplanned',
    label: 'Downtime (Planned + Unplanned)',
    description: 'Hours/days out of service',
    businessValue: 'Direct capacity loss; key indicator of maintenance efficiency',
    industry: 'leasing',
    roles: ['maintenance_manager'],
    group: 'Maintenance',
    unit: 'hours',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '30d',
    tags: ['downtime', 'maintenance'],
    thresholds: { warning: 24, critical: 72 },
    format: { decimals: 0, suffix: ' hrs' },
  },
  {
    id: 'mtbf',
    label: 'MTBF',
    description: 'Average operating hours between failures',
    businessValue: 'Reliability benchmark; key for replacement decisions',
    industry: 'leasing',
    roles: ['maintenance_manager'],
    group: 'Reliability',
    unit: 'hours',
    directionality: 'higher_is_better',
    chartType: 'kpi',
    defaultTimeRange: '90d',
    tags: ['reliability', 'mtbf'],
    thresholds: { warning: 500, critical: 200 },
    format: { decimals: 0, suffix: ' hrs' },
  },
  {
    id: 'maintenance_cost_per_mile',
    label: 'Maintenance Cost per Mile',
    description: 'Total maintenance spend ÷ miles driven',
    businessValue: 'Signals aging/expensive units; supports retire/replace decisions',
    industry: 'leasing',
    roles: ['maintenance_manager'],
    group: 'Cost',
    unit: 'currency',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '90d',
    tags: ['cost', 'maintenance'],
    format: { decimals: 3, prefix: '$' },
  },
  
  // Safety & Compliance Manager - Leasing
  {
    id: 'harsh_events_count',
    label: 'Harsh Events Count',
    description: 'Hard braking/acceleration/cornering per 1,000 miles',
    businessValue: 'Predicts risk & mechanical stress; reduces accidents and wear',
    industry: 'leasing',
    roles: ['safety_compliance_manager'],
    group: 'Safety',
    unit: 'number',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '30d',
    tags: ['safety', 'harsh'],
    thresholds: { warning: 50, critical: 100 },
    format: { decimals: 0 },
  },
  {
    id: 'speeding_violations',
    label: 'Speeding Violations',
    description: 'Speed limit breaches/time overspeed',
    businessValue: 'Key safety & fuel KPI; lowers insurance premiums',
    industry: 'leasing',
    roles: ['safety_compliance_manager'],
    group: 'Safety',
    unit: 'number',
    directionality: 'lower_is_better',
    chartType: 'timeseries',
    defaultTimeRange: '30d',
    tags: ['safety', 'speeding'],
    thresholds: { warning: 10, critical: 30 },
    format: { decimals: 0 },
  },
];

// ============================================
// Helper Functions
// ============================================

export function getMetricById(id: MetricId): MetricConfig | undefined {
  return METRICS.find(m => m.id === id);
}

export function getMetricsByIndustry(industry: IndustryId): MetricConfig[] {
  return METRICS.filter(m => m.industry === industry);
}

export function getMetricsByRole(role: RoleId): MetricConfig[] {
  return METRICS.filter(m => m.roles.includes(role));
}

export function getMetricsByIndustryAndRole(industry: IndustryId, role: RoleId): MetricConfig[] {
  return METRICS.filter(m => m.industry === industry && m.roles.includes(role));
}

export function getMetricsByGroup(group: string): MetricConfig[] {
  return METRICS.filter(m => m.group === group);
}

export function getMetricsByTag(tag: string): MetricConfig[] {
  return METRICS.filter(m => m.tags?.includes(tag));
}

export function searchMetrics(query: string): MetricConfig[] {
  const lowerQuery = query.toLowerCase();
  return METRICS.filter(m => 
    m.label.toLowerCase().includes(lowerQuery) ||
    m.description.toLowerCase().includes(lowerQuery) ||
    m.tags?.some(t => t.toLowerCase().includes(lowerQuery))
  );
}

export function getUniqueGroups(): string[] {
  const groups = new Set(METRICS.map(m => m.group).filter(Boolean));
  return Array.from(groups) as string[];
}

export function getUniqueTags(): string[] {
  const tags = new Set(METRICS.flatMap(m => m.tags || []));
  return Array.from(tags);
}

